# Generated by Django 4.1.1 on 2022-09-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task_name',
        ),
    ]
